$(function(){
    $("#name2").mouseenter(function(){setTimeout(
        $("#name2").animate({fontSize:'4em'},"fast"),10000)
    }
    );
    $("#name2").mouseleave(function(){
        $("#name2").animate({fontSize:'3em'},"fast");
    }
    ); 
});