$(function(){
    $("#name2").mouseenter(t=setTimeout(function(){
        $("#name2").animate({fontSize:'4em'},"fast");
    },200) 
    );
    $("#name2").mouseleave(function(){
        $("#name2").animate({fontSize:'3em'},"fast");
    }
    ); 
});